/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weltCrawler;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;

public class App {
    private static Random rnd = new Random();

    public String getRandomNumber(int digCount) {
        StringBuilder sb = new StringBuilder(digCount);
        for(int i = 0; i < digCount; i++)
            sb.append((char)('0' + rnd.nextInt(10)));
        return sb.toString();
    }

    public static void main(String[] args) {
        System.out.println(Arrays.toString(args));
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter number of digits (min: 1 max: 10): ");
        int digit = sc.nextInt();
        if (digit > 10 || digit <= 0) {
            System.out.println("digit to high or low");
        } else {
            System.out.println(new App().getRandomNumber(digit));
        }
    }
}
