/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weltCrawler;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        int digit = Integer.parseInt(args[0]);
        if (digit > 10 || digit <= 0) {
            System.out.println("digit to high or low");
        } else {
            System.out.println(new RandomNumberService().getRandomNumber(digit));
        }
    }
}
