/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weltCrawler;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        WeltCrawlerApp myApp = new WeltCrawlerApp();
        String output = myApp.run(args);
        System.out.println(output);
    }
}
