/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weltCrawler;

import org.junit.Assert;
import org.junit.Test;

public class AppTest {
     App.WeltCrawlerApp systemUnderTest = new App.WeltCrawlerApp();

    @Test
    public void testErrorMessage() {
        String[] givenArrayHigh = {"11"};
        String[] givenArrayLow = {"0"};
        String actualHigh = systemUnderTest.run(givenArrayHigh);
        String actualLow = systemUnderTest.run(givenArrayLow);

        Assert.assertEquals("digit too high or low", actualHigh);
        Assert.assertEquals("digit too high or low", actualLow);

    }
}

