/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weltCrawler;

import org.junit.Assert;
import org.junit.Test;

public class RandomNumberServiceTest {
    RandomNumberService systemUnderTest = new RandomNumberService();

    @Test
    public void testRightNumberOfDigits() {
        int actual = systemUnderTest.getRandomNumber(2).length();
        Assert.assertEquals(2, actual);
        Assert.assertNotEquals(4, actual);
    }

    @Test
    public void testDifferentResults() {
        String results1 = systemUnderTest.getRandomNumber(8);
        String results2 = systemUnderTest.getRandomNumber(8);
        Assert.assertNotEquals(results1, results2);
    }
}
